import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import AuthWrapper from "@/components/authwrapper";
import { Toaster } from "sonner";

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${montserrat.variable} font-sans antialiased overflow-x-hidden`}
      >
        <AuthWrapper>
          {children}
          <Toaster position="bottom-right" expand={false} richColors />
          </AuthWrapper>
      </body>
    </html>
  );
}
